package(default_visibility = ["//visibility:public"])

filegroup(
    name = "tools",
    srcs = [
        ":cc_wrapper",
        ":libtool",
        ":make_hashed_objlist.py",
        ":wrapped_ar",
        ":wrapped_clang",
        ":wrapped_clang_pp",
        ":xcrunwrapper.sh",
    ],
)

filegroup(
    name = "cc_wrapper",
    srcs = ["cc_wrapper.sh"],
)
